# Generated by Django 4.2.5 on 2023-10-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_realm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(upload_to='dream_realm/static/images/'),
        ),
    ]
