# Generated by Django 4.2.5 on 2023-10-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_realm', '0002_alter_album_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(upload_to='images/albums/covers/'),
        ),
    ]
